server:
  port: 8082

spring:
  application:
    name: product-service
  data:
    mongodb:
      uri: ${MONGO_URI:mongodb://localhost:27017/product_db}
      auto-index-creation: true
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PASSWORD:}
      ssl:
        enabled: ${REDIS_SSL:false}
      lettuce:
        pool:
          max-active: 50
          max-idle: 50
          min-idle: 10
          time-between-eviction-runs: 2000ms

eureka:
  client:
    enabled: false
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true

cloudinary:
  cloud_name: ${CLOUDINARY_CLOUD_NAME:demo}
  api_key: ${CLOUDINARY_API_KEY:123}
  api_secret: ${CLOUDINARY_API_SECRET:123}

management:
  tracing:
    enabled: false
  zipkin:
    tracing:
      endpoint: ""
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always
