server:
  port: 8082

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

spring:
  datasource:
    url: jdbc:postgresql://pg-129d92ab-ommaurya2580-d113.f.aivencloud.com:28760/defaultdb?sslmode=require
    username: avnadmin
    password: ${AIVEN_DB_PASSWORD:YOUR_PASSWORD_HERE}
  jpa:
    hibernate:
      ddl-auto: update
